import { createHash } from "node:crypto";
import { Readable } from "node:stream";
import type { FileVersion, Resource } from "@saturn/file-core";
import { describe, expect, it } from "vitest";
import { LaboratoryService } from "./laboratory.service.js";
import type { LaboratoryAsset, LaboratoryClient, LaboratoryFileGateway, LaboratoryOptions, LaboratoryRepository } from "./types.js";

const RESOURCE_ID="00000000-0000-7000-8000-000000000201";const PRIVATE_ID="00000000-0000-7000-8000-000000000202";const PASSWORD_ID="00000000-0000-7000-8000-000000000203";const V1="00000000-0000-7000-8000-000000000211";const V2="00000000-0000-7000-8000-000000000212";
const now=new Date("2026-08-26T12:00:00.000Z");
const options:LaboratoryOptions={enabled:true,publicEnabled:true,publicOrigin:"https://drive.example.test",tokenRotationGraceMs:60_000,maxConcurrentPublicStreams:1};

class MemoryRepository implements LaboratoryRepository{
  readonly clients=new Map<string,LaboratoryClient>();readonly assets=new Map<string,LaboratoryAsset>();
  async createClient(value:LaboratoryClient){this.clients.set(value.id,value);}
  async listClients(offset:number,limit:number){return[...this.clients.values()].slice(offset,offset+limit);}
  async rotateClientToken(id:string,tokenHash:string,previousTokenExpiresAt:Date,at:Date){const current=this.clients.get(id);if(!current||current.state!=="active")throw new Error("missing");const value={...current,previousTokenHash:current.tokenHash,previousTokenExpiresAt,tokenHash,updatedAt:at};this.clients.set(id,value);return value;}
  async revokeClient(id:string,at:Date){const current=this.clients.get(id);if(!current)throw new Error("missing");const value:LaboratoryClient={id:current.id,name:current.name,tokenHash:current.tokenHash,state:"revoked",createdAt:current.createdAt,updatedAt:at,revokedAt:at};this.clients.set(id,value);return value;}
  async authenticateClient(tokenHash:string,at:Date){const selected=[...this.clients.values()].find((item)=>item.state==="active"&&(item.tokenHash===tokenHash||(item.previousTokenHash===tokenHash&&(item.previousTokenExpiresAt?.getTime()??0)>at.getTime())));return selected===undefined?undefined:{client:selected,usedPreviousToken:selected.tokenHash!==tokenHash};}
  async createAsset(value:LaboratoryAsset){this.assets.set(value.id,value);return value;}
  async getAsset(id:string){return this.assets.get(id);}
  async listAssets(offset:number,limit:number){return[...this.assets.values()].slice(offset,offset+limit);}
  async updateAsset(id:string,input:Parameters<LaboratoryRepository["updateAsset"]>[1],at:Date){const current=this.assets.get(id);if(!current)throw new Error("missing");const base={...current,...(input.mode===undefined?{}:{mode:input.mode}),...(input.label===undefined?{}:{label:input.label}),...(input.disposition===undefined?{}:{disposition:input.disposition}),updatedAt:at};let value:LaboratoryAsset;if(input.pinnedVersionId===null){const{pinnedVersionId:removed,...withoutPinned}=base;void removed;value=withoutPinned;}else value={...base,...(input.pinnedVersionId===undefined?{}:{pinnedVersionId:input.pinnedVersionId})};this.assets.set(id,value);return value;}
  async disableAsset(id:string,at:Date){const current=this.assets.get(id);if(!current)throw new Error("missing");const value={...current,state:"disabled" as const,disabledAt:at,updatedAt:at};this.assets.set(id,value);return value;}
}
class MemoryFiles implements LaboratoryFileGateway{
  readonly resources=new Map<string,Resource>();readonly versions=new Map<string,FileVersion>();readonly bytes=new Map<string,Buffer>();
  async getResource(id:string){const value=this.resources.get(id);if(!value)throw new Error("missing");return value;}
  async getVersion(resourceId:string,versionId:string){const value=this.versions.get(versionId);if(!value||value.resourceId!==resourceId)throw new Error("missing");return value;}
  async openDownload(resourceId:string,offset=0,length?:number){const resource=await this.getResource(resourceId);if(!resource.currentVersionId)throw new Error("missing");const bytes=this.bytes.get(resource.currentVersionId)??Buffer.alloc(0);return{resource,stream:Readable.from(length===undefined?bytes.subarray(offset):bytes.subarray(offset,offset+length))};}
  async openVersionDownload(resourceId:string,versionId:string,offset=0,length?:number){const resource=await this.getResource(resourceId);const version=await this.getVersion(resourceId,versionId);const bytes=this.bytes.get(versionId)??Buffer.alloc(0);return{resource,version,stream:Readable.from(length===undefined?bytes.subarray(offset):bytes.subarray(offset,offset+length))};}
}
function digest(value:Buffer){return createHash("sha256").update(value).digest("hex");}
function version(id:string,resourceId:string,value:Buffer,createdAt:Date):FileVersion{return{id,resourceId,storagePath:`versions/${id}`,sha256:digest(value),sizeBytes:value.length,mimeType:"image/png",reason:"initial",state:"active",createdAt};}
function fixture(selectedOptions=options){const repository=new MemoryRepository();const files=new MemoryFiles();const first=Buffer.from("first-version");const second=Buffer.from("second-version");files.versions.set(V1,version(V1,RESOURCE_ID,first,now));files.versions.set(V2,version(V2,RESOURCE_ID,second,new Date(now.getTime()+1_000)));files.bytes.set(V1,first);files.bytes.set(V2,second);files.resources.set(RESOURCE_ID,{id:RESOURCE_ID,type:"file",parentId:"00000000-0000-7000-8000-000000000004",name:"image.png",storagePath:"sync/image.png",mimeType:"image/png",sizeBytes:first.length,sha256:digest(first),currentVersionId:V1,status:"active",securityClassification:"public",createdAt:now,updatedAt:now});files.resources.set(PRIVATE_ID,{id:PRIVATE_ID,type:"file",parentId:"00000000-0000-7000-8000-000000000004",name:"private.bin",storagePath:"sync/private.bin",mimeType:"application/octet-stream",sizeBytes:0,currentVersionId:V1,status:"active",securityClassification:"internal",createdAt:now,updatedAt:now});files.resources.set(PASSWORD_ID,{id:PASSWORD_ID,type:"file",parentId:"00000000-0000-7000-8000-000000000005",name:"saturn.kdbx",storagePath:"volt/saturn.kdbx",sizeBytes:0,currentVersionId:V1,status:"active",securityClassification:"secret",createdAt:now,updatedAt:now});return{repository,files,service:new LaboratoryService({repository,files,pepper:"p".repeat(32),options:selectedOptions})};}
async function collect(stream:Readable|undefined){if(stream===undefined)throw new Error("missing stream");const chunks=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk as Uint8Array));return Buffer.concat(chunks);}

describe("LaboratoryService",()=>{
  it("stores only HMAC client verifiers and enforces rotation/revoke",async()=>{const{service,repository}=fixture();const created=await service.createClient("Laboratory backend",now);expect(created.token).toMatch(/^[A-Za-z0-9_-]{43}$/);expect(JSON.stringify([...repository.clients.values()])).not.toContain(created.token);const privateAsset=await service.createAsset({resourceId:RESOURCE_ID,mode:"private"},now);await expect(service.deliver({assetId:privateAsset.id,filename:privateAsset.publicFilename,authorization:`Bearer ${created.token}`,head:true},now)).resolves.toMatchObject({notModified:false});const rotated=await service.rotateClient(created.client.id,new Date(now.getTime()+1_000));await expect(service.deliver({assetId:privateAsset.id,filename:privateAsset.publicFilename,authorization:`Bearer ${created.token}`,head:true},new Date(now.getTime()+2_000))).resolves.toBeDefined();await expect(service.deliver({assetId:privateAsset.id,filename:privateAsset.publicFilename,authorization:`Bearer ${rotated.token}`,head:true},new Date(now.getTime()+2_000))).resolves.toBeDefined();await service.revokeClient(created.client.id,new Date(now.getTime()+3_000));await expect(service.deliver({assetId:privateAsset.id,filename:privateAsset.publicFilename,authorization:`Bearer ${rotated.token}`,head:true},new Date(now.getTime()+4_000))).rejects.toMatchObject({code:"not_found"});});

  it("pins immutable bytes while aliases follow committed current versions and moves",async()=>{const{service,files}=fixture();const immutable=await service.createAsset({resourceId:RESOURCE_ID,mode:"public_immutable",label:"A [safe] image"},now);const alias=await service.createAsset({resourceId:RESOURCE_ID,mode:"public_alias"},now);expect(immutable.pinnedVersionId).toBe(V1);const secondVersion=files.versions.get(V2);if(secondVersion===undefined)throw new Error("missing version fixture");files.resources.set(RESOURCE_ID,{...(await files.getResource(RESOURCE_ID)),name:"moved.png",storagePath:"sync/other/moved.png",sizeBytes:secondVersion.sizeBytes,sha256:secondVersion.sha256,currentVersionId:V2,updatedAt:new Date(now.getTime()+1_000)});const pinned=await service.deliver({assetId:immutable.id,filename:"image.png"});expect((await collect(pinned.stream)).toString()).toBe("first-version");pinned.release();const current=await service.deliver({assetId:alias.id,filename:"image.png"});expect((await collect(current.stream)).toString()).toBe("second-version");current.release();expect((await service.fragment(immutable.id)).fragment).toBe(`![A \\[safe\\] image](https://drive.example.test/a/${immutable.id}/image.png)`);});

  it("enforces classification, Volt exclusion, Range, validators and stream caps",async()=>{const{service}=fixture();await expect(service.createAsset({resourceId:PRIVATE_ID,mode:"public_alias"})).rejects.toMatchObject({code:"unauthorized"});await expect(service.createAsset({resourceId:PASSWORD_ID,mode:"private"})).rejects.toMatchObject({code:"invalid"});const asset=await service.createAsset({resourceId:RESOURCE_ID,mode:"public_alias"});const ranged=await service.deliver({assetId:asset.id,filename:"image.png",range:"bytes=1-3"});expect(ranged).toMatchObject({offset:1,length:3,partial:true,cacheControl:"public, max-age=0, must-revalidate"});expect((await collect(ranged.stream)).toString()).toBe("irs");await expect(service.deliver({assetId:asset.id,filename:"image.png"})).rejects.toMatchObject({code:"limit"});ranged.release();const cached=await service.deliver({assetId:asset.id,filename:"image.png",ifNoneMatch:ranged.etag});expect(cached.notModified).toBe(true);await expect(service.deliver({assetId:asset.id,filename:"image.png",range:"bytes=0-1,3-4"})).rejects.toMatchObject({code:"range"});});

  it("keeps public delivery disabled by default",async()=>{const{service}=fixture({...options,publicEnabled:false});await expect(service.createAsset({resourceId:RESOURCE_ID,mode:"public_immutable"})).rejects.toMatchObject({code:"unauthorized"});});
});
