import { generateKeyPairSync } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { signReleaseManifest, validateProductionDeployment, verifyReleaseManifest, type ReleasePayload } from "./index.js";

const fingerprintA=`SHA256:${"A".repeat(43)}`;const fingerprintB=`SHA256:${"B".repeat(43)}`;
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"vault-deployment-"));const names=["database","owner","auth","drop","share","device","backup","laboratory"];
  names.forEach((name,index)=>fs.writeFileSync(path.join(root,name),`${name}-${String(index)}-${"x".repeat(48)}`,{mode:0o600}));fs.writeFileSync(path.join(root,"storage-key"),`-----BEGIN OPENSSH PRIVATE KEY-----\n${"A".repeat(72)}\n-----END OPENSSH PRIVATE KEY-----\n`,{mode:0o600});
  const env={NODE_ENV:"production",PUBLIC_ORIGIN:"https://vault.stage13.test",VAULT_DOMAIN:"vault.stage13.test",VAULT_VALIDATION_PROFILE:"verification",VAULT_DEPLOYMENT_ENVIRONMENT:"production",VAULT_STORAGE_ENVIRONMENT:"production",VAULT_SECRET_ROOT:root,VAULT_RELEASE_VERSION:"1.0.0",VAULT_APP_IMAGE:`registry.test/vault/app@sha256:${"a".repeat(64)}`,VAULT_WEB_IMAGE:`registry.test/vault/web@sha256:${"b".repeat(64)}`,VAULT_DEV_STORAGE_USER:"dev-user",VAULT_DEV_STORAGE_FINGERPRINT:fingerprintB,VAULT_SECOND_COPY_ID:"independent-s3-copy",VAULT_RPO_SECONDS:"21600",VAULT_RTO_SECONDS:"7200",VAULT_PUBLIC_LABORATORY_DECISION:"private",DATABASE_URL:"postgres://vault@postgres/vault",DATABASE_PASSWORD_FILE:"/run/secrets/database",OWNER_BOOTSTRAP_TOKEN_FILE:"/run/secrets/owner",AUTH_PEPPER_FILE:"/run/secrets/auth",DROP_PEPPER_FILE:"/run/secrets/drop",SHARE_PEPPER_FILE:"/run/secrets/share",DEVICE_PEPPER_FILE:"/run/secrets/device",BACKUP_PEPPER_FILE:"/run/secrets/backup",LABORATORY_PEPPER_FILE:"/run/secrets/laboratory",STORAGE_HOST:"prod.storage.test",STORAGE_USER:"prod-user",STORAGE_ROOT:".",STORAGE_HOST_FINGERPRINT:fingerprintA,STORAGE_AUTH_MODE:"private_key_file",STORAGE_PRIVATE_KEY_FILE:"/run/secrets/storage-key",LABORATORY_PUBLIC_ENABLED:"false"};return{root,env};}
const payload:ReleasePayload={schema:"vault.release-manifest.v1",componentRole:"vault-gateway",version:"1.0.0",sourceRevision:"a".repeat(40),createdAt:"2026-08-26T00:00:00.000Z",databaseSchemaGeneration:11,minimumInstallerVersion:"1.0.0",bundle:{url:"https://releases.stage13.test/vault-1.0.0.zip",sha256:`sha256:${"c".repeat(64)}`,bytes:1024},sbom:{sha256:`sha256:${"d".repeat(64)}`,format:"pnpm-licenses-json"},images:{app:`registry.test/vault/app@sha256:${"a".repeat(64)}`,web:`registry.test/vault/web@sha256:${"b".repeat(64)}`}};

describe("production deployment policy",()=>{
  it("accepts a separated production identity and protected distinct secrets",()=>{const{root,env}=fixture();try{expect(validateProductionDeployment(env)).toMatchObject({state:"valid",secretFiles:9,immutableImages:2,laboratoryExposure:"private"});}finally{fs.rmSync(root,{recursive:true,force:true});}});
  it("rejects a mutable image tag",()=>{const{root,env}=fixture();try{expect(()=>validateProductionDeployment({...env,VAULT_APP_IMAGE:"registry.test/vault/app:latest"})).toThrow(/immutable image/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
  it("rejects reuse of the declared DEV Storage identity",()=>{const{root,env}=fixture();try{expect(()=>validateProductionDeployment({...env,VAULT_DEV_STORAGE_USER:"prod-user"})).toThrow(/reuses/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
  it("signs canonical release state and rejects tampering",()=>{const{privateKey,publicKey}=generateKeyPairSync("ed25519");const privatePem=privateKey.export({type:"pkcs8",format:"pem"});const publicPem=publicKey.export({type:"spki",format:"pem"});const signed=signReleaseManifest(payload,privatePem);expect(verifyReleaseManifest(signed,publicPem)).toEqual(payload);expect(()=>verifyReleaseManifest({...signed,payload:{...payload,version:"1.0.1"}},publicPem)).toThrow(/signature/);});
});
