import { createHash, randomBytes, randomUUID } from "node:crypto";
import { Readable } from "node:stream";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const runtimeRoot=process.env.VAULT_RUNTIME_ROOT;const configModule=await import(pathToFileURL(runtimeRoot===undefined?path.join(root,"packages","config","dist","index.js"):path.join(runtimeRoot,"api","node_modules","@saturn","config","dist","index.js")));const storageModule=await import(pathToFileURL(runtimeRoot===undefined?path.join(root,"packages","storage","dist","index.js"):path.join(runtimeRoot,"api","node_modules","@saturn","storage","dist","index.js")));const config=configModule.loadEnvironment(process.env,runtimeRoot??root);if(config.environment!=="production"&&process.env.VAULT_VALIDATION_PROFILE!=="verification")throw new Error("Storage smoke requires production configuration");if(process.env.VAULT_STORAGE_ENVIRONMENT!=="production")throw new Error("Storage smoke refuses a non-production storage identity");
const storage=new storageModule.SftpStorageAdapter(config.storage);const smokeRoot="_system/smoke";const target=`${smokeRoot}/${randomUUID()}.bin`;const payload=randomBytes(1024*1024+137);const expected=createHash("sha256").update(payload).digest("hex");let deleted=false;
async function bytes(stream){const chunks=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));return Buffer.concat(chunks);}
try{if(!await storage.exists(smokeRoot))await storage.mkdir(smokeRoot);await storage.write(target,Readable.from(payload),{offset:0,create:true,exclusive:true,truncate:true});const info=await storage.stat(target);const downloaded=await bytes(await storage.openRead(target));const ranged=await bytes(await storage.openRead(target,{offset:101,length:4096}));const actual=createHash("sha256").update(downloaded).digest("hex");if(info.size!==payload.length||actual!==expected||!ranged.equals(payload.subarray(101,4197)))throw new Error("Storage smoke verification failed");await storage.delete(target);deleted=!await storage.exists(target);if(!deleted)throw new Error("Storage smoke object cleanup failed");const remaining=await storage.list(smokeRoot,undefined,2);if(remaining.entries.length===0)await storage.delete(smokeRoot);process.stdout.write(`${JSON.stringify({state:"pass",bytes:payload.length,sha256:expected,rangeBytes:ranged.length,deleted})}\n`);}finally{if(!deleted&&await storage.exists(target).catch(()=>false))await storage.delete(target).catch(()=>undefined);await storage.close().catch(()=>undefined);}
