import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import { Transform } from "node:stream";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const destinationRoot=process.argv[2]===undefined?undefined:path.resolve(process.argv[2]);const manifestPath=process.argv[3]===undefined?undefined:path.resolve(process.argv[3]);if(destinationRoot===undefined||manifestPath===undefined)throw new Error("Usage: storage-exit.mjs <empty-local-root> <manifest.json>");if(process.env.VAULT_EXIT_QUIESCED!=="true")throw new Error("Exit export requires VAULT_EXIT_QUIESCED=true");const maximum=Number(process.env.VAULT_EXIT_MAX_BYTES??5*1024*1024*1024);if(!Number.isSafeInteger(maximum)||maximum<1)throw new Error("VAULT_EXIT_MAX_BYTES is invalid");
const runtimeRoot=process.env.VAULT_RUNTIME_ROOT;const configModule=await import(pathToFileURL(runtimeRoot===undefined?path.join(root,"packages","config","dist","index.js"):path.join(runtimeRoot,"api","node_modules","@saturn","config","dist","index.js")));const storageModule=await import(pathToFileURL(runtimeRoot===undefined?path.join(root,"packages","storage","dist","index.js"):path.join(runtimeRoot,"api","node_modules","@saturn","storage","dist","index.js")));const config=configModule.loadEnvironment(process.env,runtimeRoot??root);const source=new storageModule.SftpStorageAdapter(config.storage);const destination=new storageModule.LocalStorageAdapter(destinationRoot);await destination.initialize();if((await destination.list("",undefined,1)).entries.length!==0)throw new Error("Exit destination must be empty");const files=[];let total=0;
async function hashRead(adapter,storagePath){const hash=createHash("sha256");for await(const chunk of await adapter.openRead(storagePath))hash.update(chunk);return hash.digest("hex");}
async function walk(directory){let cursor;do{const page=await source.list(directory,cursor,500);for(const entry of page.entries){if(entry.type==="directory"){await destination.mkdir(entry.path);await walk(entry.path);}else{total+=entry.size;if(total>maximum)throw new Error("Exit export exceeds VAULT_EXIT_MAX_BYTES");const hash=createHash("sha256");const tee=new Transform({transform(chunk,_encoding,callback){hash.update(chunk);callback(null,chunk);}});(await source.openRead(entry.path)).pipe(tee);await destination.write(entry.path,tee,{offset:0,create:true,exclusive:true,truncate:true});const sourceSha=hash.digest("hex");const destinationSha=await hashRead(destination,entry.path);if(sourceSha!==destinationSha)throw new Error("Alternative-backend digest comparison failed");files.push({path:entry.path,sizeBytes:entry.size,sha256:sourceSha});}}cursor=page.nextCursor;}while(cursor!==undefined);}
try{await walk("");files.sort((a,b)=>a.path.localeCompare(b.path));await fs.mkdir(path.dirname(manifestPath),{recursive:true});await fs.writeFile(manifestPath,`${JSON.stringify({schema:"vault.storage-exit.v1",createdAt:new Date().toISOString(),files,totalBytes:total},null,2)}\n`,{encoding:"utf8",mode:0o600});process.stdout.write(`${JSON.stringify({state:"pass",files:files.length,totalBytes:total,manifest:manifestPath})}\n`);}finally{await Promise.all([source.close().catch(()=>undefined),destination.close().catch(()=>undefined)]);}
